/**
 * Szavak adatok
 * 1. osztályos szavak (~125 szó)
 * 
 * MEGJEGYZÉS: A képek később kerülnek be az assets/images/words mappába.
 * A fájlnevek a szóval megegyeznek, nagybetűvel (pl. ALMA.png)
 */

export type WordItem = {
  id: string;
  word: string;
  image?: any;
  sound?: any;
  firstLetter: string;
};

export const WORDS: WordItem[] = [
  { id: "alma", word: "ALMA", firstLetter: "A" },
  { id: "angyal", word: "ANGYAL", firstLetter: "A" },
  { id: "apác", word: "APÁC", firstLetter: "A" },
  { id: "apó", word: "APÓ", firstLetter: "A" },
  { id: "ágy", word: "ÁGY", firstLetter: "Á" },
  { id: "állat", word: "ÁLLAT", firstLetter: "Á" },
  { id: "ár", word: "ÁR", firstLetter: "Á" },
  { id: "árnyék", word: "ÁRNYÉK", firstLetter: "Á" },
  { id: "árpa", word: "ÁRPA", firstLetter: "Á" },
  { id: "árva", word: "ÁRVA", firstLetter: "Á" },
  { id: "baba", word: "BABA", firstLetter: "B" },
  { id: "bár", word: "BÁR", firstLetter: "B" },
  { id: "bátor", word: "BÁTOR", firstLetter: "B" },
  { id: "béka", word: "BÉKA", firstLetter: "B" },
  { id: "bér", word: "BÉR", firstLetter: "B" },
  { id: "bélyeg", word: "BÉLYEG", firstLetter: "B" },
  { id: "bicikli", word: "BICIKLI", firstLetter: "B" },
  { id: "bika", word: "BIKA", firstLetter: "B" },
  { id: "bili", word: "BILI", firstLetter: "B" },
  { id: "bogár", word: "BOGÁR", firstLetter: "B" },
  { id: "bolt", word: "BOLT", firstLetter: "B" },
  { id: "bor", word: "BOR", firstLetter: "B" },
  { id: "bot", word: "BOT", firstLetter: "B" },
  { id: "cica", word: "CICA", firstLetter: "C" },
  { id: "cukor", word: "CUKOR", firstLetter: "C" },
  { id: "csiga", word: "CSIGA", firstLetter: "C" },
  { id: "csoki", word: "CSOKI", firstLetter: "C" },
  { id: "dada", word: "DADA", firstLetter: "D" },
  { id: "dallam", word: "DALLAM", firstLetter: "D" },
  { id: "daru", word: "DARU", firstLetter: "D" },
  { id: "déli", word: "DÉLI", firstLetter: "D" },
  { id: "dísz", word: "DÍSZ", firstLetter: "D" },
  { id: "dolgozó", word: "DOLGOZÓ", firstLetter: "D" },
  { id: "dongó", word: "DONGÓ", firstLetter: "D" },
  { id: "elem", word: "ELEM", firstLetter: "E" },
  { id: "ébred", word: "ÉBRED", firstLetter: "É" },
  { id: "ég", word: "ÉG", firstLetter: "É" },
  { id: "élelem", word: "ÉLELEM", firstLetter: "É" },
  { id: "ének", word: "ÉNEK", firstLetter: "É" },
  { id: "ér", word: "ÉR", firstLetter: "É" },
  { id: "erdő", word: "ERDŐ", firstLetter: "E" },
  { id: "eskü", word: "ESKÜ", firstLetter: "E" },
  { id: "és", word: "ÉS", firstLetter: "É" },
  { id: "étkezik", word: "ÉTKEZIK", firstLetter: "É" },
  { id: "fakó", word: "FAKÓ", firstLetter: "F" },
  { id: "fák", word: "FÁK", firstLetter: "F" },
  { id: "fal", word: "FAL", firstLetter: "F" },
  { id: "farkas", word: "FARKAS", firstLetter: "F" },
  { id: "fél", word: "FÉL", firstLetter: "F" },
  { id: "fény", word: "FÉNY", firstLetter: "F" },
  { id: "fiú", word: "FIÚ", firstLetter: "F" },
  { id: "fű", word: "FŰ", firstLetter: "F" },
  { id: "gép", word: "GÉP", firstLetter: "G" },
  { id: "golyó", word: "GOLYÓ", firstLetter: "G" },
  { id: "gyertya", word: "GYERTYA", firstLetter: "G" },
  { id: "gyöngy", word: "GYÖNGY", firstLetter: "G" },
  { id: "ház", word: "HÁZ", firstLetter: "H" },
  { id: "hal", word: "HAL", firstLetter: "H" },
  { id: "hang", word: "HANG", firstLetter: "H" },
  { id: "hét", word: "HÉT", firstLetter: "H" },
  { id: "híd", word: "HÍD", firstLetter: "H" },
  { id: "hó", word: "HÓ", firstLetter: "H" },
  { id: "igaz", word: "IGAZ", firstLetter: "I" },
  { id: "illat", word: "ILLAT", firstLetter: "I" },
  { id: "ima", word: "IMA", firstLetter: "I" },
  { id: "ír", word: "ÍR", firstLetter: "Í" },
  { id: "jár", word: "JÁR", firstLetter: "J" },
  { id: "jég", word: "JÉG", firstLetter: "J" },
  { id: "jó", word: "JÓ", firstLetter: "J" },
  { id: "kakas", word: "KAKAS", firstLetter: "K" },
  { id: "kép", word: "KÉP", firstLetter: "K" },
  { id: "kert", word: "KERT", firstLetter: "K" },
  { id: "kéz", word: "KÉZ", firstLetter: "K" },
  { id: "kis", word: "KIS", firstLetter: "K" },
  { id: "kör", word: "KÖR", firstLetter: "K" },
  { id: "köz", word: "KÖZ", firstLetter: "K" },
  { id: "kuka", word: "KUKA", firstLetter: "K" },
  { id: "kulcs", word: "KULCS", firstLetter: "K" },
  { id: "kutya", word: "KUTYA", firstLetter: "K" },
  { id: "labda", word: "LABDA", firstLetter: "L" },
  { id: "láb", word: "LÁB", firstLetter: "L" },
  { id: "lép", word: "LÉP", firstLetter: "L" },
  { id: "ló", word: "LÓ", firstLetter: "L" },
  { id: "lóca", word: "LÓCA", firstLetter: "L" },
  { id: "már", word: "MÁR", firstLetter: "M" },
  { id: "macska", word: "MACSKA", firstLetter: "M" },
  { id: "medve", word: "MEDVE", firstLetter: "M" },
  { id: "méh", word: "MÉH", firstLetter: "M" },
  { id: "méz", word: "MÉZ", firstLetter: "M" },
  { id: "mű", word: "MŰ", firstLetter: "M" },
  { id: "nap", word: "NAP", firstLetter: "N" },
  { id: "néz", word: "NÉZ", firstLetter: "N" },
  { id: "nyár", word: "NYÁR", firstLetter: "N" },
  { id: "nyúl", word: "NYÚL", firstLetter: "N" },
  { id: "óra", word: "ÓRA", firstLetter: "Ó" },
  { id: "ökör", word: "ÖKÖR", firstLetter: "Ö" },
  { id: "őz", word: "ŐZ", firstLetter: "Ő" },
  { id: "párna", word: "PÁRNA", firstLetter: "P" },
  { id: "pénz", word: "PÉNZ", firstLetter: "P" },
  { id: "pillangó", word: "PILLANGÓ", firstLetter: "P" },
  { id: "rák", word: "RÁK", firstLetter: "R" },
  { id: "rét", word: "RÉT", firstLetter: "R" },
  { id: "sár", word: "SÁR", firstLetter: "S" },
  { id: "sátor", word: "SÁTOR", firstLetter: "S" },
  { id: "siker", word: "SIKER", firstLetter: "S" },
  { id: "szár", word: "SZÁR", firstLetter: "S" },
  { id: "szél", word: "SZÉL", firstLetter: "S" },
  { id: "szín", word: "SZÍN", firstLetter: "S" },
  { id: "szó", word: "SZÓ", firstLetter: "S" },
  { id: "tányér", word: "TÁNYÉR", firstLetter: "T" },
  { id: "tér", word: "TÉR", firstLetter: "T" },
  { id: "toll", word: "TOLL", firstLetter: "T" },
  { id: "tűz", word: "TŰZ", firstLetter: "T" },
  { id: "tükör", word: "TÜKÖR", firstLetter: "T" },
  { id: "tücsök", word: "TÜCSÖK", firstLetter: "T" },
  { id: "ujj", word: "UJJ", firstLetter: "U" },
  { id: "út", word: "ÚT", firstLetter: "Ú" },
  { id: "üveg", word: "ÜVEG", firstLetter: "Ü" },
  { id: "üzlet", word: "ÜZLET", firstLetter: "Ü" },
  { id: "vár", word: "VÁR", firstLetter: "V" },
  { id: "víz", word: "VÍZ", firstLetter: "V" },
  { id: "zászló", word: "ZÁSZLÓ", firstLetter: "Z" },
  { id: "zebra", word: "ZEBRA", firstLetter: "Z" },
  { id: "zene", word: "ZENE", firstLetter: "Z" },
  { id: "zsák", word: "ZSÁK", firstLetter: "Z" },
];
