/**
 * Szavak adatok
 * 1. osztályos szavak (~125 szó)
 * 
 * MEGJEGYZÉS: A képek később kerülnek be az assets/images/words mappába.
 * A fájlnevek a szóval megegyeznek (pl. alma.png).
 */

export type WordItem = {
  id: string;
  word: string;
  image?: any;
  sound?: any;
  firstLetter: string;
};

export const WORDS: WordItem[] = [
  { id: "alma", word: "alma", firstLetter: "a" },
  { id: "angyal", word: "angyal", firstLetter: "a" },
  { id: "apác", word: "apác", firstLetter: "a" },
  { id: "apó", word: "apó", firstLetter: "a" },
  { id: "ágy", word: "ágy", firstLetter: "á" },
  { id: "állat", word: "állat", firstLetter: "á" },
  { id: "ár", word: "ár", firstLetter: "á" },
  { id: "árnyék", word: "árnyék", firstLetter: "á" },
  { id: "árpa", word: "árpa", firstLetter: "á" },
  { id: "árva", word: "árva", firstLetter: "á" },
  { id: "baba", word: "baba", firstLetter: "b" },
  { id: "bár", word: "bár", firstLetter: "b" },
  { id: "bátor", word: "bátor", firstLetter: "b" },
  { id: "béka", word: "béka", firstLetter: "b" },
  { id: "bér", word: "bér", firstLetter: "b" },
  { id: "bélyeg", word: "bélyeg", firstLetter: "b" },
  { id: "bicikli", word: "bicikli", firstLetter: "b" },
  { id: "bika", word: "bika", firstLetter: "b" },
  { id: "bili", word: "bili", firstLetter: "b" },
  { id: "bogár", word: "bogár", firstLetter: "b" },
  { id: "bolt", word: "bolt", firstLetter: "b" },
  { id: "bor", word: "bor", firstLetter: "b" },
  { id: "bot", word: "bot", firstLetter: "b" },
  { id: "cica", word: "cica", firstLetter: "c" },
  { id: "cukor", word: "cukor", firstLetter: "c" },
  { id: "csiga", word: "csiga", firstLetter: "c" },
  { id: "csoki", word: "csoki", firstLetter: "c" },
  { id: "dada", word: "dada", firstLetter: "d" },
  { id: "dallam", word: "dallam", firstLetter: "d" },
  { id: "daru", word: "daru", firstLetter: "d" },
  { id: "déli", word: "déli", firstLetter: "d" },
  { id: "dísz", word: "dísz", firstLetter: "d" },
  { id: "dolgozó", word: "dolgozó", firstLetter: "d" },
  { id: "dongó", word: "dongó", firstLetter: "d" },
  { id: "elem", word: "elem", firstLetter: "e" },
  { id: "ébred", word: "ébred", firstLetter: "é" },
  { id: "ég", word: "ég", firstLetter: "é" },
  { id: "élelem", word: "élelem", firstLetter: "é" },
  { id: "ének", word: "ének", firstLetter: "é" },
  { id: "ér", word: "ér", firstLetter: "é" },
  { id: "erdő", word: "erdő", firstLetter: "e" },
  { id: "eskü", word: "eskü", firstLetter: "e" },
  { id: "és", word: "és", firstLetter: "é" },
  { id: "étkezik", word: "étkezik", firstLetter: "é" },
  { id: "fakó", word: "fakó", firstLetter: "f" },
  { id: "fák", word: "fák", firstLetter: "f" },
  { id: "fal", word: "fal", firstLetter: "f" },
  { id: "farkas", word: "farkas", firstLetter: "f" },
  { id: "fél", word: "fél", firstLetter: "f" },
  { id: "fény", word: "fény", firstLetter: "f" },
  { id: "fiú", word: "fiú", firstLetter: "f" },
  { id: "fű", word: "fű", firstLetter: "f" },
  { id: "gép", word: "gép", firstLetter: "g" },
  { id: "golyó", word: "golyó", firstLetter: "g" },
  { id: "gyertya", word: "gyertya", firstLetter: "g" },
  { id: "gyöngy", word: "gyöngy", firstLetter: "g" },
  { id: "ház", word: "ház", firstLetter: "h" },
  { id: "hal", word: "hal", firstLetter: "h" },
  { id: "hang", word: "hang", firstLetter: "h" },
  { id: "hét", word: "hét", firstLetter: "h" },
  { id: "híd", word: "híd", firstLetter: "h" },
  { id: "hó", word: "hó", firstLetter: "h" },
  { id: "igaz", word: "igaz", firstLetter: "i" },
  { id: "illat", word: "illat", firstLetter: "i" },
  { id: "ima", word: "ima", firstLetter: "i" },
  { id: "ír", word: "ír", firstLetter: "í" },
  { id: "jár", word: "jár", firstLetter: "j" },
  { id: "jég", word: "jég", firstLetter: "j" },
  { id: "jó", word: "jó", firstLetter: "j" },
  { id: "kakas", word: "kakas", firstLetter: "k" },
  { id: "kép", word: "kép", firstLetter: "k" },
  { id: "kert", word: "kert", firstLetter: "k" },
  { id: "kéz", word: "kéz", firstLetter: "k" },
  { id: "kis", word: "kis", firstLetter: "k" },
  { id: "kör", word: "kör", firstLetter: "k" },
  { id: "köz", word: "köz", firstLetter: "k" },
  { id: "kuka", word: "kuka", firstLetter: "k" },
  { id: "kulcs", word: "kulcs", firstLetter: "k" },
  { id: "kutya", word: "kutya", firstLetter: "k" },
  { id: "labda", word: "labda", firstLetter: "l" },
  { id: "láb", word: "láb", firstLetter: "l" },
  { id: "lép", word: "lép", firstLetter: "l" },
  { id: "ló", word: "ló", firstLetter: "l" },
  { id: "lóca", word: "lóca", firstLetter: "l" },
  { id: "már", word: "már", firstLetter: "m" },
  { id: "macska", word: "macska", firstLetter: "m" },
  { id: "medve", word: "medve", firstLetter: "m" },
  { id: "méh", word: "méh", firstLetter: "m" },
  { id: "méz", word: "méz", firstLetter: "m" },
  { id: "mű", word: "mű", firstLetter: "m" },
  { id: "nap", word: "nap", firstLetter: "n" },
  { id: "néz", word: "néz", firstLetter: "n" },
  { id: "nyár", word: "nyár", firstLetter: "n" },
  { id: "nyúl", word: "nyúl", firstLetter: "n" },
  { id: "óra", word: "óra", firstLetter: "ó" },
  { id: "ökör", word: "ökör", firstLetter: "ö" },
  { id: "őz", word: "őz", firstLetter: "ő" },
  { id: "párna", word: "párna", firstLetter: "p" },
  { id: "pénz", word: "pénz", firstLetter: "p" },
  { id: "pillangó", word: "pillangó", firstLetter: "p" },
  { id: "rák", word: "rák", firstLetter: "r" },
  { id: "rét", word: "rét", firstLetter: "r" },
  { id: "sár", word: "sár", firstLetter: "s" },
  { id: "sátor", word: "sátor", firstLetter: "s" },
  { id: "siker", word: "siker", firstLetter: "s" },
  { id: "szár", word: "szár", firstLetter: "s" },
  { id: "szél", word: "szél", firstLetter: "s" },
  { id: "szín", word: "szín", firstLetter: "s" },
  { id: "szó", word: "szó", firstLetter: "s" },
  { id: "tányér", word: "tányér", firstLetter: "t" },
  { id: "tér", word: "tér", firstLetter: "t" },
  { id: "toll", word: "toll", firstLetter: "t" },
  { id: "tűz", word: "tűz", firstLetter: "t" },
  { id: "tükör", word: "tükör", firstLetter: "t" },
  { id: "tücsök", word: "tücsök", firstLetter: "t" },
  { id: "ujj", word: "ujj", firstLetter: "u" },
  { id: "út", word: "út", firstLetter: "ú" },
  { id: "üveg", word: "üveg", firstLetter: "ü" },
  { id: "üzlet", word: "üzlet", firstLetter: "ü" },
  { id: "vár", word: "vár", firstLetter: "v" },
  { id: "víz", word: "víz", firstLetter: "v" },
  { id: "zászló", word: "zászló", firstLetter: "z" },
  { id: "zebra", word: "zebra", firstLetter: "z" },
  { id: "zene", word: "zene", firstLetter: "z" },
  { id: "zsák", word: "zsák", firstLetter: "z" },
];
